#!/usr/bin/env fish

set -l self (status current-filename)
set -l file (dirname $self)/../include/merlin.hrl

echo Generating macros with arity 2-255 >&2

echo "%%% @doc This file is autogenerated, DO NOT edit by hand.
%%% Instead edit $self

-compile({parse_transform, merlin_parse_transform}).

-include(\"merlin_macros.hrl\").
" > $file

for i in (seq 2 255)
    set -l args (string join ", " (seq -f "Arg%g" $i))
    echo "-define(hygienic($args, Body), ?hygienic([$args], Body))."
    echo "-define(procedural($args, Body), ?procedural([$args], Body))."
    printf . >&2
end >> $file

echo Done >&2