%% Automatically generated by scripts/generate_in_hrl.escript
%% Do not edit by hand

-define(oneof(A),
     merlin_in_transform:'ONE OF'(A)
).

-define(oneof(A, B),
     merlin_in_transform:'ONE OF'(A, B)
).

-define(oneof(A, B, C),
     merlin_in_transform:'ONE OF'(A, B, C)
).

-define(oneof(A, B, C, D),
     merlin_in_transform:'ONE OF'(A, B, C, D)
).

-define(oneof(A, B, C, D, E),
     merlin_in_transform:'ONE OF'(A, B, C, D, E)
).

-define(oneof(A, B, C, D, E, F),
     merlin_in_transform:'ONE OF'(A, B, C, D, E, F)
).

-define(oneof(A, B, C, D, E, F, G),
     merlin_in_transform:'ONE OF'(A, B, C, D, E, F, G)
).

-define(oneof(A, B, C, D, E, F, G, H),
     merlin_in_transform:'ONE OF'(A, B, C, D, E, F, G, H)
).

-define(oneof(A, B, C, D, E, F, G, H, I),
     merlin_in_transform:'ONE OF'(A, B, C, D, E, F, G, H, I)
).

-define(oneof(A, B, C, D, E, F, G, H, I, J),
     merlin_in_transform:'ONE OF'(A, B, C, D, E, F, G, H, I, J)
).

-define(oneof(A, B, C, D, E, F, G, H, I, J, K),
     merlin_in_transform:'ONE OF'(A, B, C, D, E, F, G, H, I, J, K)
).

-define(oneof(A, B, C, D, E, F, G, H, I, J, K, L),
     merlin_in_transform:'ONE OF'(A, B, C, D, E, F, G, H, I, J, K, L)
).

-define(oneof(A, B, C, D, E, F, G, H, I, J, K, L, M),
     merlin_in_transform:'ONE OF'(A, B, C, D, E, F, G, H, I, J, K, L, M)
).

-define(oneof(A, B, C, D, E, F, G, H, I, J, K, L, M, N),
     merlin_in_transform:'ONE OF'(A, B, C, D, E, F, G, H, I, J, K, L, M, N)
).

-define(oneof(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O),
     merlin_in_transform:'ONE OF'(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O)
).

-define(oneof(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P),
     merlin_in_transform:'ONE OF'(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P)
).

-define(oneof(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q),
     merlin_in_transform:'ONE OF'(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q)
).

-define(oneof(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R),
     merlin_in_transform:'ONE OF'(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R)
).

-define(oneof(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S),
     merlin_in_transform:'ONE OF'(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S)
).

-define(oneof(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T),
     merlin_in_transform:'ONE OF'(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T)
).

-define(oneof(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U),
     merlin_in_transform:'ONE OF'(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U)
).

-define(oneof(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V),
     merlin_in_transform:'ONE OF'(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V)
).

-define(oneof(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W),
     merlin_in_transform:'ONE OF'(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W)
).

-define(oneof(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X),
     merlin_in_transform:'ONE OF'(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X)
).

-define(oneof(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y),
     merlin_in_transform:'ONE OF'(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y)
).

-define(oneof(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z),
     merlin_in_transform:'ONE OF'(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z)
).
