name: Automatic testing
on: [push]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
env:
  OTP_VERSION: "25"
  REBAR3_VERSION: "3.22"
  ERL_FLAGS: "-enable-feature maybe_expr"

jobs:
  compile-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          rebar3-version: "${{ env.REBAR3_VERSION }}"
      - name: Fetch dependencies from cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            _build/*/*/*
            ebin
          key: deps-${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.REBAR3_VERSION }}-${{ hashFiles('rebar.*') }}
      - name: Compile deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          rebar3 compile --deps_only
          rebar3 as test compile --deps_only

  compile:
    needs: [compile-deps]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          rebar3-version: "${{ env.REBAR3_VERSION }}"
      - name: Fetch dependencies from cache
        uses: actions/cache@v3
        id: cached-deps
        with:
          path: |
            _build/*/*/*
            ebin
          key: deps-${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.REBAR3_VERSION }}-${{ hashFiles('rebar.*') }}
      - name: Fetch workspace from cache
        uses: actions/cache@v3
        id: cached-workspace
        with:
          path: |
            _build/*/*/*
            ebin
          key: workspace-${{ github.ref }}
      - name: Compile
        run: |
          rebar3 compile
          rebar3 as test compile

  ct:
    needs: [compile]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          rebar3-version: "${{ env.REBAR3_VERSION }}"
      - name: Fetch workspace from cache
        uses: actions/cache@v3
        id: cached-workspace
        with:
          path: |
            _build/*/*/*
            ebin
          key: workspace-${{ github.ref }}
      - name: Run CT tests
        run: rebar3 ct

  eunit:
    needs: [compile]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          rebar3-version: "${{ env.REBAR3_VERSION }}"
      - name: Fetch workspace from cache
        uses: actions/cache@v3
        id: cached-workspace
        with:
          path: |
           _build/*/*/*
            ebin
          key: workspace-${{ github.ref }}
      - name: Run EUnit tests
        run: rebar3 eunit

  dialyzer:
    needs: [compile]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          rebar3-version: "${{ env.REBAR3_VERSION }}"
      - name: Fetch workspace from cache
        uses: actions/cache@v3
        id: cached-workspace
        with:
          path: |
            _build/*/*/*
            ebin
          key: workspace-dialyzer-${{ github.ref }}
          restore-keys:
            workspace-${{ github.ref }}
      - name: Run Dialyzer
        run: rebar3 dialyzer

  xref:
    needs: [compile]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          rebar3-version: "${{ env.REBAR3_VERSION }}"
      - name: Fetch workspace from cache
        uses: actions/cache@v3
        id: cached-workspace
        with:
          path: |
            _build/*/*/*
            ebin
          key: workspace-${{ github.ref }}
      - name: Run xref
        run: rebar3 xref
